### ISSUE TITLE
hideSelected prop for mode single

### ISSUE THREAD

**Issue by vladaCizek** [vueform/multiselect#112]
Hello and thank you for the plugin. 

Is it possible to have the "hideSelected" prop work for the default single mode? I don't see a reason, why this should not be enabled for single mode. 

Thanks!

**Comment by vladaCizek** [comment]
I've prepared a PR to solve this issue I'm having with the prop. Please check it out, I've left a comments in the description section. Just let me know, if any issue:

https://github.com/vueform/multiselect/pull/113

**Comment by adamberecz** [comment]
The problem with this is that `hideSelected` defaults to `true`. Now if we update like this everyone has to add `hideSelected: false` to each single Multiselect in their projects to keep original state. That's why we cannot have that in this version anymore, sorry.

A workaround might be to use `multiple` mode with `max: 1` and a custom label.
