### ISSUE TITLE
Created Tags disappear due to v-if

### ISSUE THREAD

**Issue by jamols09** [vueform/multiselect#152]
### Version

* Vue version: 

### Description

Multiselects created tag would disappear when inside the `v-if` condition 

1. Create your own custom tag
2. Change input from 'a' to 'b' vice versa
3. Tags inside multiselect would disappear

On the local. If selected tab is in the list of option it would not disappear only when the tag is custom.

### Demo

https://jsfiddle.net/fpw1cLj0/22/

**Comment by Glideh** [comment]
Ok I see your case now, it seems like a bug indeed.
However I think you should use a checkbox "hide" to illustrate it better in your fiddle.

Here I guess the custom tags are appended to an internal options list rather than to the immutable `options` prop.
The main issue I had in #150 is it's not showing at all, but my workaround would indeed fix your issue too :)

**Comment by adamberecz** [comment]
@jamols09 appended options are stored internally as @Glideh said. If you hide the component with `v-if` it loses it's internal state so you should use `v-show` instead:
https://jsfiddle.net/aedv3yck/
