### ISSUE TITLE
Strange behaviour when using custom data format and tags

### ISSUE THREAD

**Issue by JonMQCTR** [vueform/multiselect#212]
### Version

* Vue version: 3

### Description

When using a custom data object { id: 1, label: 'test' } for the list of objects used in the mutliselect :options prop strange behaviours are happening. 

I discovered the issue when using this with an async options call but the issues exhibit themselves in a non-async case as shown in the example code in the demo below.

Issue 1: Removing one of the pre-selected tags removes all of the tags in the v-model

Issue 2:  Pre-populating the data works when no tags are selected BUT as soon as one tag has been selected the result options are no longer displayed

Issue 3: Before removing any of the pre-selected tags the dropdown does not contain any 

The issue can be resolved by switching the options data structure to match { value: 1, label: 'test' } however this is a HUGE inconvenience when working with pre-existing API's as data then needs to be mapped when loading the parent model

### Demo

https://jsfiddle.net/1L3wnvuc/

**Comment by adamberecz** [comment]
Here's a fix:
https://jsfiddle.net/038se6Ld/

The problem was that prop names were provided with camelCase (which is not recognized in plain HTML), and `value-prop` and `label` are supposed to be `string` types but were set as non-existent variables.

To me the behaviour seems fine now, but let me know if you still experience any of the issues.

**Comment by JonMQCTR** [comment]
Perfect thanks so much for that!
