### ISSUE TITLE
when using async options, the input does not display the current v-model value

### ISSUE THREAD

**Issue by juanesarango** [vueform/multiselect#218]
For example, if I use `example #6` of your [demo](https://jsfiddle.net/xf0jzoct/), initializing it with `value: 'python`, then the current value of `v-model` is not displayed:

```js
   ...
   example6: {
      value: 'python',
      placeholder: 'Choose a programming language',
      filterResults: false,
      minChars: 1,
      resolveOnLoad: false,
      delay: 0,
      searchable: true,
      options: async (query) => {
        return await fetchLanguages(query)
      }
    },
```
<img width="665" alt="Screen Shot 2022-03-21 at 6 55 07 PM" src="https://user-images.githubusercontent.com/7906289/159334584-bd532e44-f4bd-44fa-9424-6b2bde33723d.png">

Same if I set the value dynamically with js. It's only displayed when the user does a search and clicks the option.

Is there any fix or workaround?
Thanks

**Comment by ThomasLaigneauDecathlon** [comment]
Same question here if anyone got an idea or a workaround

**Comment by antoinematyja** [comment]
I encountered the same issue.

After looking at the sources, I found out that the v-model value is not displayed because `iv` (internal value) is not correctly initialized - `iv` is `null` -> `hasSelected` computed is `false`, and the display of the single value depends on this computed value.
https://github.com/vueform/multiselect/blob/73f1b666cffc497cae85df53472aac16ceb8e89b/src/Multiselect.vue#L72

`iv` value is set by `makeInternal`:
https://github.com/vueform/multiselect/blob/73f1b666cffc497cae85df53472aac16ceb8e89b/src/composables/useOptions.js#L491-L495
https://github.com/vueform/multiselect/blob/73f1b666cffc497cae85df53472aac16ceb8e89b/src/composables/useOptions.js#L543-L555
https://github.com/vueform/multiselect/blob/73f1b666cffc497cae85df53472aac16ceb8e89b/src/composables/useOptions.js#L419-L421

In our case it will call `getOption` which requires an `options` array, but we use a function so it will not return our value.
I think a clean fix would be to return directly the value in case of function `options` param.

Until the maintainer of this repo shows up, here is a workaround:
- Use `:object="true"` (`makeInternal` will return directly the modelValue) 
- Replace `v-model="myVariable"` with `:modelValue="{ value: myVariable }"` + `@update:modelValue="myVariable = $event.value"`
  (with `object` prop, the component uses `modelValue.value`)

Kind of dirty, but works

**Comment by lippolis** [comment]
If your vue-model is a simple array of strings but is loaded with async options method, you should set this props in order to make it works:

```js
:object="true"
:modelValue="blacklist.map((item) => ({ value: item, label: item }))"
@update:modelValue="blacklist = $event.map((option) => option.label)"
```

**Comment by adamberecz** [comment]
The multiselect transform every option to the following structure `{[valueProp]: '...', [label]: '...'}` which is `{value: '...', label: '...'}` with the defaults. This happens even if you provide `options: [1,2,3]` - it will be transformed to:
```js
[
  { value: 1, label: 1 },
  { value: 2, label: 2 },
  { value: 3, label: 3 },
]
```
Just like `{a:1, b:2, c:3}` will be transformed to:
```js
[
  { value: 'a', label: 1 },
  { value: 'b', label: 2 },
  { value: 'c', label: 3 },
]
```
As multiselect has multiple ways to define options it needs to have a unified structure regardless how they are defined. This is the one works for each case.

The problem in the example is that an option needs to have a `value` and a `label` internally. If you set the `value: 'python'` the Multiselect only knows about the value, not the complete option object which includes label as well. It tries to search the options for any item that has `python` value and set it as an option. The selected items are stored as objects (eg. `{ value: 1, label: 1 }`) and not by reference of a value, because option list might change eg. on async search. When you are using `async` options with `resolveOnLoad: false` the option list is empty so `python` doesn't exist and it can't be set.

By using `object: true` and providing `value: { value: 'python', label: 'python' }` you let Multiselect know about the option object (including **value** and the **label**) so it can be set as selected even though it's not among the option list.

A possible solution to make this easier would be to display the `value` as the `label`  if it is not among the options but that introduces the problem of having to refresh the selected option objects when an option object with this value (and different label) appears among the options.

I've put together two examples to deal with use cases like this:
https://github.com/vueform/multiselect#async-options-with-default-values
https://github.com/vueform/multiselect#default-values-that-are-not-among-the-options

Feel free to continue the discussion or reopen if you have a recommendation to carry this out differently.

**Comment by juanesarango** [comment]
Thank you @adamberecz  and @antoinematyja, this solved the issue

**Comment by n14s** [comment]
@adamberecz you explanation works perfectly for `mode=multiple` and `mode=tags`.
For `single` it doesn't work unfortunately.
Using `single` results in the modelValue of the Multiselect component being correctly set, but nothing is displayed. 
I guess it's because `internalValue` is not set when using `single` in this scenario.
It is set correctly when using `mutliple` and `tags` 

Any idea how to get it working for `mode=single`?
