### ISSUE TITLE
Wrong selection if value is pre-defined array of objects

### ISSUE THREAD

**Issue by rahmanroman** [vueform/multiselect#221]
### Version

* Vue version: 3

### Description

Working with options as array of objects. If model contains some items, selection shows the first option instead of correct.

### Demo

https://jsfiddle.net/Rahman/70marnd3/

```
const app = Vue.createApp({
  data: () => ({
    example5: {
      mode: 'tags',
      value: [{name: 'robin',age: 15}, {name: 'joker', age: 42}],
      closeOnSelect: false,
      options: [{
          value: {name: 'batman', age: 100},
          label: 'Batman'
        },
        {
          value: {name: 'robin',age: 15},
          label: 'Robin'
        },
        {
          value: {name: 'joker',age: 42},
          label: 'Joker'
        },
      ]
    },
  })
})
```

![image](https://user-images.githubusercontent.com/3738055/161258150-7b7b67ae-b36a-4ed9-bdd1-5c7c463e1f8c.png)

**Comment by AlexanderVoss** [comment]
Same Problem here. Are there any Solutions for this Issue?

**Comment by cgreening5** [comment]
I've been able to get something like this working by setting the object prop to true, the modelValue prop to an array of objects like `{ name: 'batman', age: 45 }` (instead of `{ label: 'Batman', value: { name: 'batman', age: 45 } }`), the label prop set to the name of a suitable attribute of the objects, and the valueProp a unique identifier.

[https://jsfiddle.net/cgreening/85vbnyuL/9/](https://jsfiddle.net/cgreening/85vbnyuL/9/)

This worked fine in my case, but may not work for everyone. In the jsfiddle I posted, for example, the labels are not capitalized, and can't be set arbitrarily without adding an attribute to the object for that purpose.

**Comment by adamberecz** [comment]
As @cgreening5 pointed out, the correct solution is to use `object: true` & `valueProp` and provide the values as objects the same way they can be found in `options`:

```js
const app = Vue.createApp({
  data: () => ({
    example5: {
      mode: 'tags',
      valueProp: 'name',
      object: true,
      value: [
        {name: 'robin', age: 15, label: 'Robin'}, 
        {name: 'joker', age: 42, label: 'Joker'}
      ],
      closeOnSelect: false,
      options: [
        {
          name: 'batman',
          age: 100,
          label: 'Batman'
        },
        {
          name: 'robin',
          age: 15,
          label: 'Robin'
        },
        {
          name: 'joker',
          age: 42,
          label: 'Joker'
        },
      ]
    },
  })
})
```
You cannot use object values the way you wanted in the original code.
