### ISSUE TITLE
Search by label when groups is true does not work 

### ISSUE THREAD

**Issue by ejirocodes** [vueform/multiselect#264]
Expected: when I search for DC or Marvel, it should be highlighted and when clicked it add the corresponding `options`  as tag
Actual: No result found 👇🏽 
<img width="334" alt="image" src="https://user-images.githubusercontent.com/45228014/185909716-ba5120b6-a1c3-4e60-a8a6-c3701e8f2ec5.png">

```
<Multiselect
                        v-model="selectedAttributes"
                        mode="multiple"
                        :close-on-select="false"
                        :groups="true"
                        :searchable="true"
                        trackBy="label"
                        :options="[
                          {
                            label: 'DC',
                            options: ['Batman', 'Robin', 'Joker'],
                          },
                          {
                            label: 'Marvel',
                            options: [
                              'Spiderman',
                              'Iron Man',
                              'Captain America',
                            ],
                          },
                        ]"
                      />
```

**Comment by Aviv-Galmidi** [comment]
From my understanding the `label` you've set is an attribute that should exist on the group entries level not the group level

The way I solved it was to add a `searchValue` attribute like so:

```
label="name"
:searchable="true"
trackBy="searchValue"
:options="[
    {
      label: 'DC',
      options: [
        {
          name: 'Batman',
          searchValue: 'DC Batman',
        },
        {
          name: 'Robin',
          searchValue: 'DC Robin',
        },
        {
          name: 'Joker',
          searchValue: 'DC Joker',
        },
      ],
    },
    {
      label: 'Marvel',
      options: [
        {
          name: 'Spiderman',
          searchValue: 'Marvel Spiderman',
        },
        {
          name: 'Iron Man',
          searchValue: 'Marvel Iron Man',
        },
        {
          name: 'Captain America',
          searchValue: 'Marvel Captain America',
        },
      ],
    },
  ]"
```

While not the most elegant solution, it does work properly for my use case
Note that I've added a space between the group name and option name in the searchValue, which means searching for ` ` (space character) would result in all entries returned, if that's not something you want then you can adjust the `searchValue` prop to be sometihng along the lines of `DCJoker` instead of `DC Joker`

**Comment by adamberecz** [comment]
Searching for group labels is not supported but @Aviv-Galmidi's workaround seems viable.
