### ISSUE TITLE
@keydown.prevent.enter issue

### ISSUE THREAD

**Issue by batuotasis** [vueform/multiselect#54]
Currently I set `:add-tag-on="[]"` and handle tagging carefully by testing every key typed with regex before addition.

Unfortunately I cannot implement features like `on enter jump to next input`, `on enter do other stuff like add tag manually or display html5 validation message if something is wrong`.

Could you provide option to turn `@keydown.prevent.enter` off so developers can handle this feature by themselves?

I think this won't take much time to implement and will make your component much more flexible.

**Comment by adamberecz** [comment]
`@keydown.prevent.enter` is only on the container div, there are other keyup and keydown events on search inputs depending on which mode you use, so that's not quite straightforward. I wouldn't go into giving too much freedom in handling basic key events like enter to avoid overcomplicating things. If you need to implement such specific behavior I'd it's best to override the component template and implement key events as they fit you the best.
