### ISSUE TITLE
trackBy on multiple properties

### ISSUE THREAD

**Issue by MiC11w** [vueform/multiselect#57]
I need search capability to work with multiple properties. Can I use 'trackBy'  for that? Or is there some other method?

**Comment by adamberecz** [comment]
Concatenating a string in `trackBy` could be a solution?

**Comment by rafalolszewski94** [comment]
Coming back to this issue, since this could be a good improvement to the component.

Maybe allow users to set similar property as `trackBy`, like `alias` to be used as aliased.

----

**Good example is search location component.**

There was a spelling change from _Turkey_ to _Türkiye_

I have a const that composes of few lodash utilties and creates an array for Multiselect.

```js
export const EUROPE_COUNTRIES = [
  'Sweden',
  'Türkiye',
]

export const COUNTRY_CHOICES = intersectionBy(
  orderBy(
    EUROPE_COUNTRIES.map((c) => {
      if (c === 'Türkiye') {
        return {
          label: c,
          value: c,
          alias: ['Turkey'],
        }
      }
      return {
        label: c,
        value: c,
      }
    }),
    [(country) => country.value.toLowerCase()],
    ['desc']
  ),
  'label'
)
```

```vue
<Multiselect
  v-model="location"
  :options="COUNTRY_CHOICES"
  searchable
  placeholder="Select locations"
  trackAlias="alias"
/>
```

**Comment by morrowcreative** [comment]
Is here any update please?

**Comment by adamberecz** [comment]
As of `2.6.3` `trackBy` can be an array @morrowcreative

**Comment by morrowcreative** [comment]
Thank you very much :) @adamberecz
