### ISSUE TITLE
Typescript types definition

### ISSUE THREAD

**Issue by danielhgasparin** [vueform/multiselect#8]
Please, add types definition for Typescript support.

**Comment by leifcr** [comment]
@danielhgasparin If you are good at typescript definitions, please review #19

**Comment by danielhgasparin** [comment]
Approved. I'm not an expert in Typescript, but tested on my project and worked well.

I didn't validate every properties and events of the component, though. But the typescript and intelisense recognized the type and compiled well.

**Comment by yaquawa** [comment]
I'm wondering will this project switch to ts in the near future?

**Comment by adamberecz** [comment]
Help me out here. If Typescript is added sure it helps the development of the library, but what's in it for the end user? I'm trying to test this implementation in VSCode with Vetur but a) it does not suggest properties when using the component in `<template>` nor it throws a compile error when defining invalid props (except for the built-in Vue prop typechecking at runtime).

**Comment by yaquawa** [comment]
@adamberecz I can confirm that Vetur won't give any useful info for custom component in `components`, that was surprising me too...

For the moment I could suppress the ts complier error by adding a declaration for the package.
```ts
declare module '@vueform/multiselect' {}
```

But, still I'm looking forward it can be typescriptized, because this is the best vue3 mutiselect component I can find in the market :) Thanks for the great work really !
